#################################################################
######################  Hexo Configuration#######################
######################  专门用于gh pages #########################


url: https://gitychzh.github.io/hskt_pages #设配GH pages,想要GH pages 能正常访问，必须要有此配置
root: /hskt_pages/