#################################################################
######################  Hexo Configuration#######################
######################  专门用于cf pages #########################

url: https://hskt-pages.pages.dev #设配CF pages
root: /